#! /bin/bash
#$Author: ee364b06 $
#$Date: 2016-01-12 15:03:00 -0500 (Tue, 12 Jan 2016) $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364b06/Lab00/Script1 $
#$Revision: 83992 $

Num_Of_Param=$#
Param_Values=$@
echo "The program recieved $Num_Of_Para parameters"
echo "The parameters are: "
echo "$Param_Values"
echo "The 2nd parameter is \"$2\""
echo "The 4nd parameter is \"$4\""
exit 0

