#! /bin/bash
#$Author: ee364b06 $
#$Date: 2016-01-12 15:18:53 -0500 (Tue, 12 Jan 2016) $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364b06/Lab00/Script2 $
#$Revision: 84003 $

Param_Values=$@
for ((I=0;I<Param_Values;I++))
do 
let result=$Param_Values-$I
echo "$result"
done
exit 0

